### ISSUE TITLE
AZ-Touch Pi0 with Kernel >5.4

### ISSUE THREAD

**Issue by ItFinallyWorks** [LoveBootCaptain/WeatherPi_TFT#33]
Hello, 
maybe i am making a mistake i don´t get, but i is it possible  that the external display from the AZ-Touch Pi0 does not work with the current kernel version?

I tried several times to set the system up acccording to the readme and everything works fine (display has power, weatherdisplay on hdmi works well, variables are set properly....), except it does not show up on  the external displayl.

I would be thankful for any hint.

regards
Matthias

**Comment by llevet** [comment]
Hi,

Yes it need a new overlay file because the wiring of the TFT is different to the standard overlay rpi-display.

Make the modification given here : 
https://github.com/HWHardsoft/AZ-Touch-Pi0-Weather/issues/3

After this, compile with : 
dtc -@ -I dts -O dtb -o rpi-display.dtbo rpi-display-overlay.dts

and in final : 
mv /boot/overlays/rpi-display.dtbo /boot/overlays/rpi-display.dtbo.org
cp rpi-display.dtbo /boot/overlays/rpi-display.dtbo

Reboot and all is done.

Ludo.

**Comment by LoveBootCaptain** [comment]
AZ-Touch users should use @HWHardsoft installation guide: https://github.com/HWHardsoft/AZ-Touch-Pi0-Weather
RaspianOS is currently not supported for AT-Touch or WasperPi_TFT.
I will update the readme concerning that issue.
